# Generated by Django 4.0.5 on 2022-07-06 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 12, 46, 40, 340752, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 12, 46, 40, 372676, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='glucose',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 12, 46, 40, 367690, tzinfo=utc)),
        ),
    ]
