# Generated by Django 4.0.5 on 2022-07-06 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Readings', '0004_alter_bloodp_date_alter_bmi_date_alter_glucose_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 14, 51, 5, 624219, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 14, 51, 5, 624219, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='glucose',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 14, 51, 5, 624219, tzinfo=utc)),
        ),
    ]
