# Generated by Django 4.0.5 on 2022-07-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Readings', '0005_alter_bloodp_date_alter_bmi_date_alter_glucose_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodp',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='glucose',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
