# Generated by Django 5.0.2 on 2024-03-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Patient", "0002_alter_patient_height_alter_patient_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="age",
            field=models.IntegerField(null=True),
        ),
    ]
